sources:
  - name: staging
    database: big-brother-brasil-454420
    schema: bigbrotherbrasil

    tables:
      - name: Contestants
      - name: ranking
      - name: ratingaverage
      - name: evictionresults1
      - name: evictionresults2
      - name: evictionresults3
      - name: evictionresults4
      - name: evictionresults5
      - name: evictionresults6
      - name: evictionresults7
      - name: evictionresults8
      - name: evictionresults9
      - name: evictionresults10
      - name: evictionresults11
      - name: evictionresults12
      - name: evictionresults13
      - name: evictionresults14
      - name: evictionresults15
      - name: evictionresults16
      - name: evictionresults17
      - name: evictionresults18
      - name: evictionresults19
      - name: evictionresults20
      - name: evictionresults21
      - name: evictionresults22
      - name: evictionresults23
      - name: evictionresults24
      - name: evictionresults25
      - name: nominations1
      - name: nominations2
      - name: nominations3
      - name: nominations4
      - name: nominations5
      - name: nominations6
      - name: nominations7
      - name: nominations8
      - name: nominations9
      - name: nominations10
      - name: nominations11
      - name: nominations12
      - name: nominations13
      - name: nominations14
      - name: nominations15
      - name: nominations16
      - name: nominations17
      - name: nominations18
      - name: nominations19
      - name: nominations20
      - name: nominations21
      - name: nominations22
      - name: nominations23
      - name: nominations24
      - name: nominations25
      - name: ratingsweekly1
      - name: ratingsweekly2
      - name: ratingsweekly3
      - name: ratingsweekly4
      - name: ratingsweekly5
      - name: ratingsweekly6
      - name: ratingsweekly7
      - name: ratingsweekly8
      - name: ratingsweekly9
      - name: ratingsweekly10
      - name: ratingsweekly11
      - name: ratingsweekly12
      - name: ratingsweekly13
      - name: ratingsweekly14
      - name: ratingsweekly15
      - name: ratingsweekly16
      - name: ratingsweekly17
      - name: ratingsweekly18
      - name: ratingsweekly19
      - name: ratingsweekly20
      - name: ratingsweekly21
      - name: ratingsweekly22
      - name: ratingsweekly23
      - name: ratingsweekly24
      - name: ratingsweekly25


